version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'lockfile-only' # Only updates yarn.lock, not package.json
    labels: # Automatically adds labels to PRs
      - 'dependencies'
      - 'yarn'
    commit-message: # Customizes commit messages
      prefix: 'yarn' # Adds "yarn:" to regular dependency updates
      prefix-development: 'yarn dev' # Adds "yarn dev:" to devDependency updates
