name: Android Build Only (Tag/Manual) - v4

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for (prod or dev)'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with Yarn Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle Packages
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache EAS CLI
        id: cache-eas
        uses: actions/cache@v3
        with:
          path: ~/.eas-cli
          key: ${{ runner.os }}-eas-${{ hashFiles('**/eas.json') }}
          restore-keys: |
            ${{ runner.os }}-eas-

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK and AAB
        env:
          EXPO_PUBLIC_DEBUG: ${{ github.event.inputs.environment == 'dev' && 'true' || 'false' }}
        run: |
          echo "Building with EXPO_PUBLIC_DEBUG: $EXPO_PUBLIC_DEBUG"
          npx eas-cli build --platform android --profile production --local --non-interactive --output app-production.aab
          npx eas-cli build --platform android --profile preview --local --non-interactive --output app-preview.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app-preview.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app-production.aab

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'GitHub Actions: Android Build ${{ job.status }}'
          body: |
            Android Build workflow has ${{ job.status }}.

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Triggered by: ${{ github.actor }}
          to: ${{ secrets.MAIL_RECIPIENT }}
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
