name: Android APK Build & Release (Tag or Manual Trigger) v2

on:
  push:
    tags:
      - 'v*' # Trigger on tag push that starts with 'v'
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: write # Grant permissions to create and upload releases
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-gradle-default

      - name: Cache EAS build
        uses: actions/cache@v3
        with:
          path: ~/.eas-cli
          key: ${{ runner.os }}-eas-${{ hashFiles('**/eas.json') }}
          restore-keys: |
            ${{ runner.os }}-eas-
            ${{ runner.os }}-eas-default

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android app
        run: |
          npx eas-cli build --platform android \
            --profile production \
            --local --non-interactive \
            --output app-production-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app-production-release.apk

      - name: Create Release and Upload APK
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_NAME="Release $TAG_NAME"
          if ! gh release view $TAG_NAME > /dev/null 2>&1; then
            gh release create "$TAG_NAME" app-production-release.apk \
              --title "$RELEASE_NAME" \
              --notes "APK for version $TAG_NAME"
          else
            gh release upload "$TAG_NAME" app-production-release.apk --clobber
          fi
