name: Android APK & AAB Build & Release v3

on:
  push:
    tags:
      - 'v*' # Trigger on tag push that starts with 'v'
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: write # Grant permissions to create and upload releases
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Create Yarn cache directory
        run: mkdir -p ~/.cache/yarn

      - name: Install dependencies
        run: |
          echo "Installing dependencies with Yarn..."
          yarn install --frozen-lockfile
          echo "Yarn cache size after installation:"
          du -sh ~/.cache/yarn

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-gradle-default

      - name: Check Gradle cache status
        run: |
          if [[ "${{ steps.cache-gradle.outputs.cache-hit }}" == 'true' ]]; then
            echo "✅ Gradle cache hit!";
          else
            echo "❌ Gradle cache miss. Dependencies will be installed.";
          fi

      - name: Cache EAS build
        id: cache-eas
        uses: actions/cache@v3
        with:
          path: ~/.eas-cli
          key: ${{ runner.os }}-eas-${{ hashFiles('**/eas.json') }}
          restore-keys: |
            ${{ runner.os }}-eas-
            ${{ runner.os }}-eas-default

      - name: Check EAS cache status
        run: |
          if [[ "${{ steps.cache-eas.outputs.cache-hit }}" == 'true' ]]; then
            echo "✅ EAS cache hit!";
          else
            echo "❌ EAS cache miss. EAS will be set up.";
          fi

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK and AAB
        run: |
          npx eas-cli build --platform android --profile production --local --non-interactive --output app-production.aab
          npx eas-cli build --platform android --profile preview --local --non-interactive --output app-preview.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app-preview.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app-production.aab

      - name: Create Release and Upload APK & AAB
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_NAME="Release $TAG_NAME"
          if ! gh release view $TAG_NAME > /dev/null 2>&1; then
            gh release create "$TAG_NAME" app-preview.apk app-production.aab \
              --title "$RELEASE_NAME" \
              --notes "APK and AAB for version $TAG_NAME"
          else
            gh release upload "$TAG_NAME" app-preview.apk app-production.aab --clobber
          fi
